In [1]:
import pandas as np

In [ ]:
# Rodando o CSV transações  bancárias
import pandas as pd

df = pd.read_csv("transacoes_bancarias.csv")

df.head()

,id_transacao,id_cliente,tipo_transacao,valor,data_transacao,conta_origem,conta_destino,descricao
0,1,144,saque,4938.32,2025-02-06 03:23:00,Conta H,NaN,Saque
1,2,143,deposito,1314.72,2025-02-20 18:45:00,Conta I,NaN,Depósito
2,3,106,transferencia,4173.77,2025-01-27 23:08:00,Conta J,Conta G,Transferência
3,4,121,deposito,2987.08,2025-01-02 07:47:00,Conta D,NaN,Depósito
4,5,118,transferencia,1363.74,2025-01-18 00:03:00,Conta D,Conta I,Transferência

In [ ]:
#Estrutura Geral
#O dataset é composto por variáveis numéricas, categóricas e temporais.
#As colunas id_transacao e id_cliente são do tipo inteiro, a coluna valor é numérica contínua, data_transacao é do tipo datetime, e as colunas tipo_transacao, conta_origem, conta_destino e descricao são variáveis categóricas.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_transacao    500 non-null    int64
 1   id_cliente      500 non-null    int64
 2   tipo_transacao  500 non-null    str
 3   valor           500 non-null    float64
 4   data_transacao  500 non-null    str
 5   conta_origem    500 non-null    str
 6   conta_destino   165 non-null    str
 7   descricao       500 non-null    str
dtypes: float64(1), int64(2), str(5)
memory usage: 31.4 KB

In [4]:
#Conversão de data 
df['data_transacao'] = pd.to_datetime(df['data_transacao'])

In [ ]:
#A coluna data_transacao foi convertida para o tipo datetime utilizando a função pd.to_datetime(), permitindo a realização de análises temporais como agrupamento por mês e ano.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_transacao    500 non-null    int64
 1   id_cliente      500 non-null    int64
 2   tipo_transacao  500 non-null    str
 3   valor           500 non-null    float64
 4   data_transacao  500 non-null    datetime64[us]
 5   conta_origem    500 non-null    str
 6   conta_destino   165 non-null    str
 7   descricao       500 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 31.4 KB

In [ ]:
# A análise de valores mostrou que apenas a coluna conta_destino possui valores ausentes.
df.isnull().sum()

id_transacao        0
id_cliente          0
tipo_transacao      0
valor               0
data_transacao      0
conta_origem        0
conta_destino     335
descricao           0
dtype: int64

In [ ]:
#A análise de valores distintos foi realizada com o método df.nunique(), permitindo identificar a diversidade de informações presentes em cada coluna do dataset.
df.nunique()

id_transacao      500
id_cliente         51
tipo_transacao      3
valor             500
data_transacao    498
conta_origem       10
conta_destino      10
descricao           3
dtype: int64

In [ ]:
#Tratamento de valores nulos
#No tratamento dos dados, os valores nulos identificados na coluna conta_destino foram preenchidos com o valor “Não se aplica”, pois transações do tipo saque e depósito não possuem conta de destino.
df['conta_destino'] = df['conta_destino'].fillna('Não se aplica')

In [9]:
#Verificação de valores constantes
#Não foram identificadas colunas com valores constantes no dataset, indicando variabilidade adequada para análise.
df.nunique()

id_transacao      500
id_cliente         51
tipo_transacao      3
valor             500
data_transacao    498
conta_origem       10
conta_destino      11
descricao           3
dtype: int64

In [ ]:
# Verificação de valores inválidos
#Não foram encontrados valores negativos ou zerados na coluna valor.
df[df['valor'] <= 0]

Empty DataFrame
Columns: [id_transacao, id_cliente, tipo_transacao, valor, data_transacao, conta_origem, conta_destino, descricao]
Index: []

In [11]:
# Pergunta 1
#Qual o total movimentado por tipo de transação?
df.groupby('tipo_transacao')['valor'].sum()

tipo_transacao
deposito         414124.35
saque            407641.91
transferencia    418880.44
Name: valor, dtype: float64

In [12]:
# Pergunta 2
#Qual o valor médio das transações por tipo?
df.groupby('tipo_transacao')['valor'].mean()

tipo_transacao
deposito         2421.779825
saque            2485.621402
transferencia    2538.669333
Name: valor, dtype: float64

In [13]:
#Pergunta 3
#Quais são os 5 clientes que mais movimentaram dinheiro?
df.groupby('id_cliente')['valor'].sum().sort_values(ascending=False).head(5)

id_cliente
146    40674.51
113    39849.72
108    39182.83
140    38604.11
114    38132.99
Name: valor, dtype: float64

In [14]:
#Pergunta 4
#Qual o volume total movimentado por mês?

df['mes'] = df['data_transacao'].dt.to_period('M')

df.groupby('mes')['valor'].sum()

mes
2025-01    670810.79
2025-02    553132.55
2025-03     16703.36
Freq: M, Name: valor, dtype: float64

In [15]:
#Pergunta 5
#Quais foram as contas de origem que mais realizaram transferências?

df[df['tipo_transacao'] == 'transferencia'] \
    .groupby('conta_origem')['valor'] \
    .sum() \
    .sort_values(ascending=False)

conta_origem
Conta D    64745.17
Conta C    59578.48
Conta B    50681.97
Conta A    45049.46
Conta E    44307.29
Conta H    40264.12
Conta J    35691.23
Conta G    31017.40
Conta I    28493.08
Conta F    19052.24
Name: valor, dtype: float64